[tool.poetry]
name = "ehroes"
version = "1.0.0"
description = "My main application for the handling, cleaning and processing of myopathy patient health data"
authors = ["Corentin Meyer <corentin.meyer@etu.unistra.fr>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7.1,<4.0"
pip = "*"
setuptools = "*"
wheel = "*"
scikit-learn = "^1"
scikit-image = "^0"
dash = "^2"
Flask = "^2"
Flask-WTF = "^0"
WTForms = "^2"
wtforms-validators = "^1"
Flask-Login = "^0"
Flask-SQLAlchemy = "^2"
Flask-Mail = "^0"
python-dotenv = "^0"
pandas = "^1.3"
numpy = "^1"
plotly = "^5"
CairoSVG = "^2"
Pillow = "^8"
joblib = "^1"
dash-core-components = "^2"
dash-bootstrap-components = "^1"
Flask-Migrate = "^3"
Flask-Session = "^0"
pytesseract = "^0"
pdf2image = "^1"
spacy = "^3"
thefuzz = "^0"
email-validator = "^1"
dash-html-components = "^2"
gunicorn = "^20"
opencv-python-headless = "^4"
python-Levenshtein = "^0.12.2"
black = {extras = ["jupyter"], version = "^21.9b0"}
PyJWT = "^2.3.0"

[tool.poetry.dev-dependencies]
ipykernel = "^6"
pylint = "^2.11"
pylint-flask-sqlalchemy = "^0"
pylint-flask = "^0"
black = "*"
unittest2 = "^1"
pytest = "^6.2.5"
bandit = "^1.7.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
