[tool.poetry]
name = "myoxia"
version = "1.0.0"
description = "My main application for the handling, cleaning and processing of myopathy patient health data"
authors = ["Corentin Meyer <corentin.meyer@etu.unistra.fr>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
pip = "*"
setuptools = "*"
wheel = "*"
scikit-learn = "*"
scikit-image = "*"
dash = "*"
Flask = "*"
Flask-WTF = "*"
WTForms = "*"
wtforms-validators = "*"
Flask-Login = "*"
jwt = "*"
Flask-SQLAlchemy = "*"
Flask-Mail = "*"
python-dotenv = "*"
pandas = "*"
numpy = "*"
plotly = "*"
CairoSVG = "*"
Pillow = "*"
joblib = "*"
dash-core-components = "*"
dash-bootstrap-components = "<1"
Flask-Migrate = "*"
Flask-Session = "*"
pytesseract = "*"
pdf2image = "*"
spacy = "*"
thefuzz = "*"
email-validator = "*"
dash-html-components = "*"
gunicorn = "*"
opencv-python-headless = "*"

[tool.poetry.dev-dependencies]
ipykernel = "*"
pylint = "*"
pylint-flask-sqlalchemy = "*"
pylint-flask = "*"
black = "*"
unittest2 = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
